# 1. NumPy Exercises 

Fill in the blanks with the instruction code for a fulfilled program.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array "number" of 10 zeros 

In [2]:

number = np.zeros(10)
print(number)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array "number2" of 10 ones

In [3]:

number2 = np.ones(10)
print(number2)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array "number3" of each item =5 ( in array have 10 items)

In [7]:
number3 = np.full(10, 5)
print(number3)


[5 5 5 5 5 5 5 5 5 5]


#### Create an array "number4" of the integers from 10 to 50  with funciton arange()

In [9]:
number4 = np.arange(10, 51)
print(number4)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array "number5"of all the even integers from 10 to 50

In [10]:
number5 = np.arange(10, 51, 2)
print(number5)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix "a1" with values ranging from 0 to 8 using function arange() and reshape()

In [6]:

matrix = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

#### Create matrix array "a2" 3x3 matrix with values [[12,13,14,15], [17, 18, 19, 20],[22, 23, 24, 25]]

In [13]:
a2 = np.array([[12, 13, 14, 15], [17, 18, 19, 20], [22, 23, 24, 25]])
print(a2)


[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


#### change reshape from 4 row 3 column

In [18]:
a3 = a2.reshape(4, 3)
print(a3)

[[12 13 14]
 [15 17 18]
 [19 20 22]
 [23 24 25]]


#### select column 2 and all row to show in [13,17,20,24]

In [19]:
selected_column = a3[:, 1]
print(selected_column)



[13 17 20 24]


#### change array matrix "a2" to 1D array (flatten)

In [20]:
a2_flattened = a2.flatten()
print(a2_flattened)


[12 13 14 15 17 18 19 20 22 23 24 25]


#### find summation in array metrix "a2" using funtion sum()

In [21]:
summation = np.sum(a2)
print(summation)


222


# Good Job!